# Generated by Django 5.1.15 on 2026-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'Əlaqə saxlanıldı'), ('closed', 'Bağlanıb')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_start',
            field=models.DateField(blank=True),
        ),
    ]
