# Generated by Django 5.1.15 on 2026-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplierpurchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchase',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('cancelled', 'Ləğv edildi')], default='active', max_length=20),
        ),
    ]
