# Generated by Django 5.1.15 on 2026-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Users", "İstifadəçilər"),
                            ("Wrench", "Alət"),
                            ("Boxes", "Qutular"),
                            ("Truck", "Yük maşını"),
                            ("Wallet", "Cüzdan"),
                            ("BarChart3", "Qrafik"),
                            ("ShieldCheck", "Qalxan"),
                            ("Printer", "Printer"),
                            ("Gauge", "Sürətölçən"),
                            ("Lock", "Kilid"),
                            ("Puzzle", "Tapmaca"),
                            ("Smile", "Gülümsəmə"),
                            ("MonitorSmartphone", "Monitor/Telefon"),
                            ("Check", "Tik"),
                            ("Star", "Ulduz"),
                        ],
                        default="Check",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Users", "İstifadəçilər"),
                            ("Wrench", "Alət"),
                            ("Boxes", "Qutular"),
                            ("Truck", "Yük maşını"),
                            ("Wallet", "Cüzdan"),
                            ("BarChart3", "Qrafik"),
                            ("ShieldCheck", "Qalxan"),
                            ("Printer", "Printer"),
                            ("Gauge", "Sürətölçən"),
                            ("Lock", "Kilid"),
                            ("Puzzle", "Tapmaca"),
                            ("Smile", "Gülümsəmə"),
                            ("MonitorSmartphone", "Monitor/Telefon"),
                            ("Check", "Tik"),
                            ("Star", "Ulduz"),
                        ],
                        default="Check",
                        max_length=30,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[("primary", "Əsas (mavi)"), ("dark", "Tünd")],
                        default="primary",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                (
                    "points",
                    models.TextField(blank=True, help_text="Hər sətirdə bir bənd"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("number", models.CharField(default="1", max_length=5)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="SERVIO", max_length=60)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Loqonun yanında və ya footer-də qısa şüar",
                        max_length=200,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Boş saxlansa, hazırkı statik loqo işləyir",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Servisinizi daha rahat idarə edin.", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="Müştərilər, təmirlər, gəlir-xərc, anbar, borclar və hesabatlar — hamısı bir platformada. Telefon və kompüter servis bizneslər üçün ağıllı idarəetmə sistemi.",
                    ),
                ),
                ("email", models.EmailField(default="info@servio.az", max_length=254)),
                ("phone", models.CharField(default="+994 50 000 00 00", max_length=32)),
                (
                    "whatsapp",
                    models.CharField(
                        default="994500000000",
                        help_text="wa.me üçün, + və boşluqsuz",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(default="Bakı, Azərbaycan", max_length=200),
                ),
                (
                    "hours",
                    models.CharField(
                        default="Bazar ertəsi – Şənbə, 09:00 – 18:00", max_length=120
                    ),
                ),
                ("footer_note", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sayt ayarları",
                "verbose_name_plural": "Sayt ayarları",
            },
        ),
    ]
