# Generated by Django 6.1.1 on 2026-09-22 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashboxOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='tenants.branch')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='tenants.shop')),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Gəlir'), ('expense', 'Xərc'), ('supplier_payment', 'Təchizatçı ödənişi')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('bank_transfer', 'Bank köçürməsi')], default='cash', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('expense_category', models.CharField(blank=True, help_text='Elektrik, İcarə, Maaş və s.', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='tenants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='repairs.repairorder')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='tenants.shop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'type', 'created_at'], name='finance_cas_shop_id_1c1191_idx')],
            },
        ),
    ]
