# Generated by Django 5.1.15 on 2026-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Gəlir'), ('expense', 'Xərc'), ('supplier_payment', 'Təchizatçı ödənişi'), ('refund', 'Geri qaytarma (zəmanət)')], max_length=20),
        ),
    ]
