# Generated by Django 5.1.15 on 2026-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cashtransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Kassa'), ('expense', 'Xərc'), ('supplier_payment', 'Təchizatçı ödənişi'), ('refund', 'Geri qaytarma (zəmanət)')], max_length=20),
        ),
    ]
