# Generated by Django 6.1.1 on 2026-09-22 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('max_users', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(help_text='Giriş üçün: istifadeci.KOD', max_length=60, unique=True)),
                ('owner_full_name', models.CharField(blank=True, max_length=150)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('logo_initials', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('trial', 'Sınaq müddətində'), ('active', 'Aktiv'), ('overdue', 'Ödəniş gecikib'), ('blocked', 'Bloklanıb')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('next_payment_at', models.DateField(blank=True, null=True)),
                ('default_warranty_days', models.PositiveIntegerField(default=14)),
                ('currency', models.CharField(default='AZN', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='tenants.plan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.shop')),
            ],
            options={
                'ordering': ['-is_main', 'name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'name'), name='unique_branch_name_per_shop')],
            },
        ),
    ]
