# Generated by Django 5.1.15 on 2026-09-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, help_text='Qəbzdə görünəcək ünvan', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, help_text='Qəbzdə görünəcək telefon', max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='receipt_terms',
            field=models.TextField(blank=True, default='1. Zəmanət yalnız görülən işə və dəyişdirilən detala şamil olur, cihazın digər hissələrinə aid deyil.\n2. Fiziki zədə, maye təması və üçüncü şəxs müdaxiləsi zəmanəti ləğv edir.\n3. Təmir bitdikdən sonra cihaz 30 gün ərzində götürülməlidir, bu müddətdən sonra servis saxlama üçün məsuliyyət daşımır.\n4. Cihaz yalnız bu sənəd və şəxsiyyət vəsiqəsi təqdim edildikdə təhvil verilir.', help_text='Qəbzin altında görünəcək zəmanət/təhvil-təslim şərtləri'),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VÖEN (istəyə bağlı)', max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='work_hours',
            field=models.CharField(blank=True, help_text='Məs: B.e – Şənbə 10:00–19:00', max_length=120),
        ),
    ]
