# Generated by Django 5.1.15 on 2026-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_shop_address_shop_phone_shop_receipt_terms_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["sort_order", "price_monthly"]},
        ),
        migrations.AddField(
            model_name="plan",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text='"Ən populyar" kimi vurğulanır'
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="public_description",
            field=models.CharField(
                blank=True,
                help_text="Qiymətlər səhifəsində planın altındakı qısa izah",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="public_features",
            field=models.TextField(blank=True, help_text="Hər sətirdə bir üstünlük"),
        ),
        migrations.AddField(
            model_name="plan",
            name="show_on_pricing_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
