# Generated by Django 5.1.15 on 2026-10-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_plan_options_plan_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='disabled_reason',
            field=models.CharField(blank=True, help_text='Mağaza bağlıdırsa səbəb — avtomatik (ödəniş vaxtı keçib) və ya Baş Admin tərəfindən əl ilə yazılıb. Giriş zamanı istifadəçiyə bu mətn göstərilir.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Söndürülübsə, bu mağazanın HEÇ BİR istifadəçisi giriş edə bilmir.'),
        ),
    ]
