# Generated by Django 5.1.15 on 2026-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_shop_disabled_at_shop_disabled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='İllik ödəniş seçimi (AZN). Boş saxlansa, Qiymətlər səhifəsində illik seçim göstərilmir.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='public_description_yearly',
            field=models.CharField(blank=True, help_text="İllik ödəniş seçimi göstəriləndə onun altında görünən qısa izah (məs. '2 ay pulsuz').", max_length=200),
        ),
    ]
