# Generated by Django 6.1.1 on 2026-09-22 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('repairs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Sifariş anındakı qiymət (snapshot)', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('bank_transfer', 'Bank köçürməsi')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('accepted', 'Qəbul edildi'), ('rejected', 'Rədd edildi'), ('paid', 'Ödənilib'), ('shipped', 'Göndərilib'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='pending', max_length=20)),
                ('buyer_note', models.CharField(blank=True, max_length=255)),
                ('seller_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.branch')),
                ('buyer_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_purchases', to='tenants.shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to='inventory.product')),
                ('related_repair', models.ForeignKey(blank=True, help_text='Hansı təmir üçün lazımdır (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_orders', to='repairs.repairorder')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_requests', to=settings.AUTH_USER_MODEL)),
                ('seller_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_sales', to='tenants.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('buyer_shop', models.F('seller_shop')), _negated=True), name='marketplace_buyer_seller_differ')],
            },
        ),
    ]
