# Generated by Django 5.1.15 on 2026-09-30 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_unique_sku_per_shop_and_more'),
        ('marketplace', '0001_initial'),
        ('repairs', '0002_repairwarrantyreturn'),
        ('tenants', '0002_shop_address_shop_phone_shop_receipt_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketplaceorder',
            name='marketplace_buyer_seller_differ',
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_shop__lt', models.F('seller_shop')), ('buyer_shop__gt', models.F('seller_shop')), _connector='OR'), name='marketplace_buyer_seller_differ'),
        ),
    ]
