# Generated by Django 6.1.1 on 2026-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('repairs', 'Təmir / Xidmətlər'), ('customers', 'Müştərilər'), ('inventory', 'Anbar'), ('marketplace', 'Marketplace (mağazalararası bazar)'), ('suppliers', 'Təchizatçılar'), ('cashbox', 'Kassa — bütün əməliyyatlar'), ('expenses', 'Xərclər'), ('debts', 'Borclar — ümumi məbləğ'), ('reports', 'Hesabatlar / Analitika'), ('users', 'İstifadəçilər və icazələr'), ('settings', 'Parametrlər'), ('revenue_numbers', 'Gəlir / net mənfəət rəqəmləri')], max_length=32),
        ),
    ]
