# Generated by Django 5.1.15 on 2026-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_rolepermission_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(
                default=False,
                help_text='DİQQƏT: bu BÜTÜN mağazaları görən Platforma Super Adminidir. Yalnız BİR mağazanın admini olsun deyə bunu YOX, "Mağaza" + "Rol" (Sahib) sahələrini doldurun.',
            ),
        ),
    ]
