# Generated by Django 5.1.15 on 2026-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_is_platform_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_shop_admin",
            field=models.BooleanField(
                default=False,
                help_text="Bu istifadəçi öz mağazasının Platforma panelinə daxil ola bilsin (yalnız öz mağazasının məlumatlarını görür/redaktə edir). Rol sistemindən tamam ayrıdır.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(
                default=False,
                help_text='DİQQƏT: bu BÜTÜN mağazaları görən Platforma Super Adminidir. Yalnız BİR mağazanın admini olsun deyə bunu YOX, aşağıdakı "Mağaza admini" sahəsini işarələyin.',
            ),
        ),
    ]
