# Generated by Django 6.1.1 on 2026-09-22 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, help_text='Ekran, Batareya, Anakart və s.', max_length=80)),
                ('sku', models.CharField(blank=True, help_text='Daxili kod', max_length=60)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('min_stock_alert', models.PositiveIntegerField(default=2, help_text='Bu miqdardan aşağı düşəndə xəbərdarlıq')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Maya dəyəri', max_digits=10)),
                ('unit_sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Öz servisin satış qiyməti', max_digits=10)),
                ('is_shared_to_marketplace', models.BooleanField(default=False, help_text='Aktiv olarsa, digər mağazaların ustaları bu məhsulu axtarışda görüb sifariş göndərə bilər')),
                ('marketplace_price', models.DecimalField(blank=True, decimal_places=2, help_text='Digər mağazalara satış qiyməti (boşdursa unit_sale_price istifadə olunur)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepairPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost_at_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_usages', to='inventory.product')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='repairs.repairorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Alış (daxil olma)'), ('repair_use', 'Təmirdə istifadə (sərfiyyat)'), ('adjustment', 'Əl ilə düzəliş'), ('marketplace_out', 'Başqa mağazaya satış'), ('marketplace_in', 'Başqa mağazadan alış')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Müsbət: daxil olma, Mənfi: çıxış')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('related_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='repairs.repairorder')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'name'], name='inventory_p_shop_id_23b50f_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('shop', 'sku'), name='unique_sku_per_shop'),
        ),
    ]