# Generated by Django 5.1.15 on 2026-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_scrap',
            field=models.BooleanField(default=False, help_text='Zəmanət altında qaytarılıb, təchizatçı qəbul etməyib — satışa çıxarılmır (Zay anbarı)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'Alış (daxil olma)'), ('repair_use', 'Təmirdə istifadə (sərfiyyat)'), ('adjustment', 'Əl ilə düzəliş'), ('marketplace_out', 'Başqa mağazaya satış'), ('marketplace_in', 'Başqa mağazadan alış'), ('warranty_rejected_in', 'Zəmanət qaytarması (təchizatçı qəbul etmədi)')], max_length=20),
        ),
    ]
