# Generated by Django 5.1.15 on 2026-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_scrap_alter_stockmovement_movement_type'),
        ('tenants', '0002_shop_address_shop_phone_shop_receipt_terms_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_per_shop',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('shop', 'sku'), name='unique_sku_per_shop'),
        ),
    ]
