# Generated by Django 5.1.15 on 2026-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_unique_sku_per_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=False, help_text='İkinci əl (istifadə olunmuş) məhsuldur — yeni deyil'),
        ),
    ]
