"""Django admin (Jazzmin) parametrləri."""

JAZZMIN_SETTINGS = {
    "site_title": "Servio Admin",
    "site_header": "Servio",
    "site_brand": "Servio",
    "welcome_sign": "Servio admin panelinə xoş gəldiniz",
    "copyright": "Servio",
    "search_model": ["tenants.Shop", "accounts.User"],
    "user_avatar": None,

    "topmenu_links": [
        {"name": "Ana səhifə", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Platforma (sayt)", "url": "http://localhost:3000/platform", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],

    "order_with_respect_to": [
        "tenants", "accounts", "platform_admin",
        "customers", "repairs", "inventory", "suppliers", "finance", "marketplace",
    ],

    "icons": {
        "accounts": "fas fa-users-cog",
        "accounts.User": "fas fa-user",
        "accounts.Role": "fas fa-user-shield",
        "tenants": "fas fa-store",
        "tenants.Shop": "fas fa-store-alt",
        "tenants.Branch": "fas fa-code-branch",
        "tenants.Plan": "fas fa-layer-group",
        "platform_admin": "fas fa-crown",
        "platform_admin.SupportTicket": "fas fa-headset",
        "platform_admin.SubscriptionPayment": "fas fa-credit-card",
        "customers": "fas fa-address-book",
        "customers.Customer": "fas fa-user-friends",
        "repairs": "fas fa-tools",
        "repairs.RepairOrder": "fas fa-wrench",
        "inventory": "fas fa-boxes",
        "inventory.Product": "fas fa-box",
        "inventory.StockMovement": "fas fa-dolly",
        "inventory.RepairPartUsage": "fas fa-cog",
        "suppliers": "fas fa-truck",
        "suppliers.Supplier": "fas fa-truck-loading",
        "finance": "fas fa-wallet",
        "finance.CashTransaction": "fas fa-money-bill-wave",
        "finance.CashboxOpeningBalance": "fas fa-cash-register",
        "marketplace": "fas fa-shopping-basket",
        "marketplace.MarketplaceOrder": "fas fa-exchange-alt",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
